server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend-system
          __path__: /var/log/*log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            env: env
            context: context

      - timestamp:
          source: timestamp
          format: RFC3339

      - labels:
          level:
          env:
